os: osx
language: go
script:
- "./create-and-load-cert.sh"
- "./download-and-sign.sh"
- "./verify.sh"
- "./verify-against-controlplane.sh"
env:
  global:
  # travis encrypt --add KUBECTL_URL=https://....
  - secure: KRfJd++wPNTkk1shfBaqQtI6FvRECExNtIydKq/bE9lgxSZmfRBji2IrObi7cbNPTTKtrwYNtuKt79Z5JoZ4HhRzmz5Wxo0Vs1yAcBFIX/1/AuKAlwEdKXRPA//+8WKcuCWBOHFI4fxejDwZGGGR1KfhkHktZfZsFf1yDf7+PKTCXRHhMIVQHzljVB+Zi9tz1LyNFGrDUoWT6OiSXp7enQTpx8AMFIzrU+rPr4fBBxmmfvFTdCYvt0PRsYmkYWLzjx1TIkb6t+H0QthmSn7jB4t3sGPP5CzFrtziUnIekxUbgxaAm347fiXbV6gz5e5XqTHDsp6Reqr44mzuLFek3NGDnxNtNo2r5fokPuIYfe31KJOLpPD8LvQn8fQO0fBDIqBi6+EfE90EcyOCrbHWuDgbdSFa+JcJ5ILn2cVheXZYOIZwLuNL5zK3dsQ0Tfrbf0HtgZdauPaIaTEICd0S8LyziVr4ub+TNU40daviT8+ony6FeFh7a1UogZuA+O4NCoejKLtGra3kE/FFAetJ/rZpsEuKHUdryDWHDWhMVZvFxNpyv80kjCHO2lVdxPGciZ3GeKnt7nKqDkNQcBZX2BmWbKECGp7Ss62+vlxKZmpJeWdZrnwiZ7c51Mr3NBxqS9Sgpyk/tp81twxtvH+iyLomgFtup3qxaS4961Vak9I=
