os: osx

services:
- docker

script:
- ./create-and-load-cert.sh
- ./download-and-sign.sh
- ./verify.sh
- docker info

env:
  global:
    # travis encrypt --add KUBECTL_URL=https://....
    secure: gDMx/+PiA1Sk5FAla65cI/nq5y3yLNIGNNMVBCH9lgV5oBo5i0tKFqPQUCuHVbpOeJ0jOxOt67XcoPAcr0mia/xC0+OwHMZmUnC3g4JWPTgQKQP13DGM/jkGqv0lJnZORRON9hKXvshrcTLMB8QjVbU2RoigciwZKPdaT2XEOnhZTKuZlZoeS+iOJQ6Ihuj3oDtVLqlJ4FYlFRPIJZy7C2R+LT6feLe8n/idBpDTNlePENT5M1G0yG30gRZFGkFC4Nil9Ym9MGrVadHnBSTtUNHHXyu5O4eB0t+OrclHyhrRDgtc2VpTGIgyLI1Z7c17MgTir1cWXgnX0qMRlH/ml7KyWZgq2MMw2wlbiVHzLA1/ca1lFrUMwuUiGqAZxH/rIv7ozX8sH0SEGGlUlrVPa42r+qCpujY3gMRAgr51zo9XjEZAnThXY7uLcHKujCM5HhXpPKlRXlHClVJ9o5sBMcz3xzjn6ecLnl3xswWVXgbNr2MlzHxltYYArykwSFiqELgR8pRxnch4o2amDbi+3syA/vP/3zNmUDAd296aEV8O/1ai/fYUJEbWWVeMxCrYifriKSV9yCe2adW5niiM6o3QaL9SxfCqBl8OMTXkxOckW6oA/UsXUJlUdcyuQOoWbYbRX80R6sWAG+nLGXfzKE3nSDqHavZM4GopckeVjdE=
